### ISSUE TITLE
Timer of a scene does not work any more

### ISSUE THREAD

**Issue by MrRikkie** [domoticz/Machinon#12]
When I go to my scenes and then select from a specific scene the timer settings I get the screen as shown below.
![2020-05-01_15-00-01](https://user-images.githubusercontent.com/30286668/80807184-ca28b780-8bbc-11ea-81c2-2f9159bb5cb1.jpg)

I use Version: 2020.2 of domoticz.

**Comment by davidlb** [comment]
Can you check the browser console (F12) and report here the error mesages?

**Comment by MrRikkie** [comment]
Hello, 
I just checked the ERRORS and this is what I get : 

Uncaught ReferenceError: VM126:62
setDeviceSwitch is not defined
    at HTMLDivElement.<anonymous> 
(<anonymous>:62:21)
    at Function.each (jquery-3.4.1.min.js:2)
    at k.fn.init.each (jquery-3.4.1.min.js:2)
    at setAllDevicesFeatures 
(<anonymous>:23:27)
    at <anonymous>:228:17

TypeError: angular.min.js:124 
sceneApi.getSceneInfo is not a function
    at init (SceneTimersController.js:19)
    at new <anonymous> (SceneTimersController.js:13)
    at Object.instantiate (angular.min.js:44)
    at angular.min.js:95
    at Object.link (angular-route.min.js:7)
    at angular.min.js:17
    at va (angular.min.js:85)
    at p (angular.min.js:71)
    at f (angular.min.js:62)
    at angular.min.js:62 "<div id="main-view" ng-view="" class="ng-scope" data-ng-animate="1">"

Best Regards, Erik

**Comment by davidlb** [comment]
Thanks for your feedback, I'm finally able to reproduce it, I'm now looking for a way to fix it.

**Comment by davidlb** [comment]
It's probably an issue with the cache as I fixed it by changing the theme to the default one and then changing back to machinon.  Go to the theme settings and click on theme reset button to clear your browser cache.
I hope it will fix it for you too.

**Comment by MrRikkie** [comment]
Hi, thnx for your feedback. Seems to be solved if i follow your steps.

Thank you very much for developing and maintaining this theme, it works great and had a very nice design. Keep up the good work.
