### ISSUE TITLE
Problem display devices after update domoticz build 14855

### ISSUE THREAD

**Issue by Ptifredy** [domoticz/Machinon#124]
Hello everyone,

Since the last 2 versions of Domoticz, Machinon displays each device across the width of the page on Dashboard, Utility, ...
I tried emptying the cache, in private and on another browser and nothing worked.

Domoticz Version: 2022.2 (build 14855)
Machinon V.1.17.5
Raspberry Pi3 - Debian 10 (buster)

Last build 14870, same problem.

Before update Domoticz - OK
<img width="837" alt="MachinonOK" src="https://user-images.githubusercontent.com/12476899/208739477-96e7e740-fb1b-4011-8830-fbb986709753.png">

After update Domoticz - Machinon Broken
<img width="1055" alt="MachinonBroken" src="https://user-images.githubusercontent.com/12476899/208739581-52300952-14f8-4ff0-8129-ac726e3a9bc7.png">

**Comment by mkampstra** [comment]
Same here. But in my installation it only appears on Dashboard. When press Ctrl+F5, it is ok for 3-4 seconds and after that it is over the whole screen.
All the other pages, like switches and scenes are working fine. No shifting.

**Comment by BreizhCat** [comment]
Hello

I have the same issue there via the last beta 14870.
Everything works fine except the dashboard.

**Comment by cvc90** [comment]
I have the same problem in Version: 2022.2 (build 14863)

@Ptifredy Would you be so kind as to tell me how you have achieved this degraded background or what options have you applied in Domoticz to achieve it? Thank you

**Comment by Ptifredy** [comment]
@cvc90 It's a background 
![Background017](https://user-images.githubusercontent.com/12476899/209386780-56d84eb8-4f4e-4119-9c35-229964450587.jpg)

**Comment by cvc90** [comment]
@Ptifredy Thank you! And you also have dark mode activated right?

**Comment by BreizhCat** [comment]
Hi 

Maybe it can help to understand this issue but I have only have the issue on my local network 192.168.x.x.
If I access to Domoticz through my domain it works well.

**Comment by sebekhtc** [comment]
hi, 
windows11, Edge - all fine.
Firefox same bug as reported. Clearing the cash (even twice, additional one after switching back to dafult theme and back) didn't help. Could it be related to some recent firefox update?

**Comment by DewGew** [comment]
I tryed with latest beta today and it seems to work better now. I also removed the new domoticz search in latest version since we dont need it for machinon template.

**Comment by Ptifredy** [comment]
I confirm, since the last versions it is much better.

**Comment by sebekhtc** [comment]
Working properly. Still not sure which machinon theme to use as I have two folders/themes: Machinon and machinon (first choice machinon looks working allright). The Machinon folder reappears after delete and fresh installation of machinon theme

**Comment by Ptifredy** [comment]
@sebekhtc verify if use Domoticz Theme Manager plugin and disable it.

**Comment by sebekhtc** [comment]
Thanks, you were right, I had it enabled.
