### ISSUE TITLE
Domoticz 2023.1 : login page without style

### ISSUE THREAD

**Issue by fab85170** [domoticz/Machinon#129]
Hi, I've upgraded to domoticz 2023.1
All seems to work with the theme, exept for the login page that seems to doesn't have style.
The page is white, but we can enter the credentials.
Could you advice?

Thanks

**Comment by Erwanweb** [comment]
Hi, I have same problem more or less, at first connexion, login page have not style, bu can enter credential and clic to connect. After be connected, dashboard haven't too style, need to refresh, and it is ok.
If go to setup and clic deconnect, login page have style, if refresh the login page, come back to login page without style.
I tryed this on PC with firefox and Chrome, on iphone with chrome and Safari, all same issue.
Someone have an idea for this issue. ? 
Maybe @DewGew

**Comment by fab85170** [comment]
Yes it's exactly the same issue...

**Comment by jfalmeida** [comment]
same here
