### ISSUE TITLE
Font color makes text not readable

### ISSUE THREAD

**Issue by bikeymouse** [domoticz/Machinon#13]
Initially [posted](https://www.domoticz.com/forum/viewtopic.php?p=248077#p248051) on Domoticz forum (with screenshot):

++++

Great theme, much better then the default 90's Windows XP look ;-) Thanks for all your work.

I only have some requests for visual improvement with V 1.15.4 (which I know, of course is beta):

The first one: using dark mode, I find the blue entries on the dark background in the logfile quite difficult to read. Would it be possible to change this to a white font, like in all other overviews, such as the devices list?

Secondly, also in dark mode: in set-up/hardware devices, all the parameter entry boxes are grey with the contents in a black font, which is hardly readable. The same for the room-selector drop-down box on the right hand corner of the device, scenes, dashboard etc. pages. It shows the selected room name is using a black-font on a grey background.

And lastly, (also in dark mode): if you want to add a new device to a room (settings/room plan/room plan), a list of all devices is presented. The lines are alternating on a white or gray background. Unfortunately the letters are always white, so half of the list seems empty (it took me a while to figure out why I couldn't find some devices!).

**Comment by davidlb** [comment]
Thanks for your report
Fixed in 1.15.5
