### ISSUE TITLE
Theme setup

### ISSUE THREAD

**Issue by one1973** [domoticz/Machinon#134]
Theme setup content keep loading after last update, caché cleared, service restarted...

**Comment by DewGew** [comment]
Have you updated the theme?

**Comment by one1973** [comment]
Yes.... right now.... after restart, cache cleared.. etc... setup keep loading....

**Comment by DewGew** [comment]
Hit F12 see if there is any error in console

**Comment by one1973** [comment]
custom.js:36     GET http://MYURL:8070/json.htm?type=command&param=getsettings 401 (Unauthorized)

**Comment by one1973** [comment]
that file doesn't exist

**Comment by one1973** [comment]
or I don't find it... because, the next msg....

yntaxError: Unexpected token '<', "<html><hea"... is not valid JSON

**Comment by one1973** [comment]
ok... the problem for Unaotorized :

add 127.0.0.* to LOCAL NETWORK withpout user/password... but still problem with the theme, is impossible to change to dark theme, or aplly custom colors to the heme.

**Comment by DewGew** [comment]
You need latest stable domoticz
