### ISSUE TITLE
No more edit button on devices

### ISSUE THREAD

**Issue by TroisSix** [domoticz/Machinon#135]
Hi,
Your theme is the best one, and I cannot use another one as yours is simply clear and beautiful :)

I did an update at the end of july to get the last version, and I shouldn't have done it as now I cannot see any edit button on my devices.

It tried on Firefox and Chrome: same behaviour.
I cleared the caches and restarted a lot of times the browsers, tested the private windows (anonymous), restarted domoticz a lot of time, but now way to recover my edit buttons.
I precise that I have tested all the other themes and all of them have the edit button (dafault, aurora, dark-th3me, osiTransparent, element-light, ...)

What should I do?

Thx for your help ^^

**Comment by rnollen** [comment]
I have the same issue. It worked OK for quit some while, I updated the theme and now it does not work correctly anymore. Edit buttons are not present and the Menu layout is broken. Cleared the cache inprivate / incognito..reinstalled the entire theme, but no luck there. Any help is appreciated.

**Comment by DewGew** [comment]
Still an issue?

**Comment by TroisSix** [comment]
Sure as there wasn't any update of the release master or beta.
I was using the classic theme of Domoticz. I just changed the theme to the machinon with a new git clone, and I still have the issue.

**Comment by DewGew** [comment]
Strange I dont have this issue, Im rinning latest beta of domoticz

**Comment by DewGew** [comment]
> Sure as there wasn't any update of the release master or beta. I was using the classic theme of Domoticz. I just changed the theme to the machinon with a new git clone, and I still have the issue.

Hit F12 (chrome) then selct console. see i you find any errors. Also you can try right click console is open right click on refresh button then select "empty cache and then hard refresh"
