### ISSUE TITLE
Air quality (CO2) sensors have no button on mobile dashboard

### ISSUE THREAD

**Issue by svollebregt** [domoticz/Machinon#14]
Hi,

First of all: great theme! I've been using the Machinon theme for a while now and noticed that on the mobile dashboard air quality sensors have no arrow button next to the name. Clearing the cache does not resolve the issue. See also the attached image.
![20200601_135228](https://user-images.githubusercontent.com/42436341/83407073-43ac0380-a410-11ea-8b08-1c9d0dfde675.jpg)

I am using Machinon 1.15.4 and the latest Domoticz beta (12106). The issue exists in both Chrome mobile as the Samsung browser.

**Comment by davidlb** [comment]
Thanks for your report
Fixed in 1.15.5
