### ISSUE TITLE
Blinds icons do not fit with slider barr

### ISSUE THREAD

**Issue by Rouzax** [domoticz/Machinon#142]
Running that latest Beta build of Domoticz and the latest Master branch of Machinon

Both on my mobile and desktop browser, the Blinds icons and slider bar don't fit properly
![image](https://github.com/domoticz/Machinon/assets/4103090/74aa0e6f-e0bf-41e6-8fb2-b6b6292c2717)

![image](https://github.com/domoticz/Machinon/assets/4103090/54e03691-c193-483b-96ee-5aa5a37a9370)

Using latest Firefox on both

**Comment by DewGew** [comment]
Ive adjust css file. Try out latest

**Comment by Rouzax** [comment]
Looks much better!
![image](https://github.com/domoticz/Machinon/assets/4103090/8069d5db-58e5-4910-860d-b4b4bc136cb7)
