### ISSUE TITLE
Sensor in "off" state shows switch in "on" state

### ISSUE THREAD

**Issue by DeKnep** [domoticz/Machinon#17]
My doorbell is hooked up to a GPIO pin, which Domoticz recognizes as a switch device. I've set its type to "doorbell".
Obviously, its state is usually "off".
However, when I enable "Switch instead of text" for the machinon theme, the device shows a switch in the "on" state.

![Deurbel](https://user-images.githubusercontent.com/67982317/86848815-fd049580-c0ae-11ea-82f1-1b21ec64d24e.jpg)

I would have expected either no switch at all (preferred, since it's a sensor) or a switch showing the correct value.

**Comment by davidlb** [comment]
Fixed by @DewGew in beta branch
