### ISSUE TITLE
[visual bugs] Dark mode improvs

### ISSUE THREAD

**Issue by chrislader** [domoticz/Machinon#19]
Hi there,

Noticed some visual things to improve the best UI :)

1:
Adding devices on Roomplan is white on white. You need to select text to see devices
![image](https://user-images.githubusercontent.com/40333466/87131432-b1134580-c294-11ea-8bb5-31641f9f2cfd.png)

2:
In general, the black text on dark grey is hard to read sometimes. I think it's an overall improvement to replace the color with grey:
![image](https://user-images.githubusercontent.com/40333466/87132157-c0df5980-c295-11ea-9111-cb353949d775.png)

All in all, this is by far the best interface for Domoticz in my opinion. Good luck, David :)

**Comment by davidlb** [comment]
Hi Chris, most of these bugs have been fixed in 1.15.5
I will just change the column header for the next release, thanks for your report !

**Comment by chrislader** [comment]
Thanks David, love it! Just updated to 15.5. Works like a charm.

Did find another bug. But will post it since it is not UI related.
