### ISSUE TITLE
Refresh/search bug at temperature screen

### ISSUE THREAD

**Issue by chrislader** [domoticz/Machinon#23]
this is when I search for "Delta" it shows just 1 result:
![image](https://user-images.githubusercontent.com/40333466/87798614-86089300-c84c-11ea-83c4-cf5a63c950e0.png)

The screen 'adds' other sensors when they give an updated value
So the same screen looks like this after 1 minute:

![image](https://user-images.githubusercontent.com/40333466/87798743-acc6c980-c84c-11ea-9928-ebac322342e2.png)

It looses the focus on the search result it appears. I have tested the Utility screen; there it keeps the search result in focus.

Might be a Domoticz bug as well, don't know?

**Comment by davidlb** [comment]
Yeah, it's strange, it happens only in few screens,
Anyway, I apply again filters after device refresh and it's ok.
