### ISSUE TITLE
[Python Plugin] Domoticz Theme Manager

### ISSUE THREAD

**Issue by galadril** [domoticz/Machinon#26]
Hi

I just wanted to let you know, that people can install and auto update this theme in Domoticz via the Domoticz Theme Manager (Python plugin)
https://github.com/galadril/domoticz-theme-manager

Can you maybe add this info to the Readme??

Mark

**Comment by davidlb** [comment]
Thanks @galadril for this new plugin, I'll update the readme with the next coming release.
