### ISSUE TITLE
[visual bug] dark mode, camera and device edit screen

### ISSUE THREAD

**Issue by chrislader** [domoticz/Machinon#28]
Hi David,

Another screen found where the UI can be improved;
When I edit the camera, the text is white.

I can image that we keep the text white, but we make the screens dark :) 

Machinon theme V.1.15.5

![image](https://user-images.githubusercontent.com/40333466/88640367-2917a300-d0be-11ea-8489-9ebdd32d85bf.png)

Same goes for device edit screens: 
Utility, weather and temperature are WHITE.
Edit screen of switches and scenes is OK.

![image](https://user-images.githubusercontent.com/40333466/88640571-60864f80-d0be-11ea-8457-d8f7c84e3c25.png)

![image](https://user-images.githubusercontent.com/40333466/88640830-afcc8000-d0be-11ea-9320-2ce4ae64c18c.png)

![image](https://user-images.githubusercontent.com/40333466/88640999-e904f000-d0be-11ea-95a0-48fff3fc1a56.png)

**Comment by chrislader** [comment]
edit the bugs; i can image we keep the text white, but convert these screens into dark mode :)

**Comment by davidlb** [comment]
As you mentioned it, I changed the background of the popup to be consistent with the theme ;)
