### ISSUE TITLE
Dashboard disappears in 1.16.1 in mobile browser

### ISSUE THREAD

**Issue by svollebregt** [domoticz/Machinon#32]
Just updated to 1.16.1 and on mobile devices the dashboard disappears after it has been shown for 1 sec. Other tabs like switches work. I already reset the theme and cleared the cache. Also in the incognito mode this happens. Browser is Chrome for Android.

On a desktop or when using desktop mode in the mobile browser it works fine. Is this an issue on my side or due to a code change?

**Comment by 1337LutZ** [comment]
Experiencing the same here 👍

**Comment by Riesjah** [comment]
Same problem here

**Comment by davidlb** [comment]
I'm on the vacation, I'll fix when I'm back before end of August.

**Comment by DeKnep** [comment]
Great, thanks already :-)
I did some testing with different versions; the issue seems to be caused by commit 59e8681f0d8261262c90b41039c12e464537c160.

**Comment by heggink** [comment]
commenting out line 92 (the one that was added in that commit) in custom.js fixes stuff indeed.

**Comment by Plantje1978** [comment]
Is that this line?
/*                searchFunction(); */

Commenting it out doesn't help in my case...

**Comment by heggink** [comment]
That's it indeed. No idea why it does not work. It does for me.

**Comment by Plantje1978** [comment]
My bad.... I thought this would fix the misalignment in the events script tab as well. It doesn't and it is nowhere suggested it does :)
