### ISSUE TITLE
Buttons in Events misaligned in 1.16.1

### ISSUE THREAD

**Issue by Xenomes** [domoticz/Machinon#33]
The buttons are misaligned, the save and delete not visual.

Pictures say more then words...
![afbeelding](https://user-images.githubusercontent.com/11648297/89176522-fe2fc200-d589-11ea-8b25-566714e8ac2b.png)

**Comment by Plantje1978** [comment]
+1
I have the same issue.

**Comment by chrislader** [comment]
Same here. I dont think they are 'misaligned', I think David used center aligned code. 

So its also about taste. Same goes for the buttons on the dashboard page.

@davidlb to be honest I wouldnt use the center alignment that much. It was better the previous way...

**Comment by davidlb** [comment]
Argh it's a side effect, I didn't catch before releasing! I'll try to fix it soon

**Comment by DewGew** [comment]
In 1.15.5 it looks good

**Comment by davidlb** [comment]
Fixed in beta

**Comment by Plantje1978** [comment]
Tested beta and it is fixed indeed.
