### ISSUE TITLE
Items background are transparent using background image (1.16.1)

### ISSUE THREAD

**Issue by Xenomes** [domoticz/Machinon#34]
Items background are transparent when using background image.

![afbeelding](https://user-images.githubusercontent.com/11648297/89177306-6c28b900-d58b-11ea-9a27-d6e420637879.png)

**Comment by davidlb** [comment]
Fixed in beta

**Comment by Xenomes** [comment]
Very nicely done. Big thanks!
![afbeelding](https://user-images.githubusercontent.com/11648297/91060146-e4364c00-e62a-11ea-8e54-730ee7e21221.png)
