### ISSUE TITLE
Double scrollbars in log

### ISSUE THREAD

**Issue by DeKnep** [domoticz/Machinon#35]
The log shows double scrollbars.
This means you have to scroll down with the outermost scrollbar to see the latest log lines. But if you do, then the All / Status / Error tabs scroll out of view. So to reach those, you have to scroll back up again. This is quite annoying.

Expected behavior: no outer scrollbar (like in the default theme).

![Log_double_scrollbars](https://user-images.githubusercontent.com/67982317/90425231-ba77a500-e0bf-11ea-979b-8f068e721a53.jpg)

Seen in both Firefox and Chrome on Windows 10.

**Comment by davidlb** [comment]
Fixed in beta
