### ISSUE TITLE
Feature request: custom timestamp format

### ISSUE THREAD

**Issue by DeKnep** [domoticz/Machinon#37]
I have the language in Domoticz set to English and the "Show Last Seen as Time ago" option for Machinon switched off.
This results in American style AM/PM timestamps for "last seen". Being European, I'm used to a 24-hour clock though. The default theme also uses a 24-hour format.

It would be nice to have an option to specify a custom timestamp format.

**Comment by davidlb** [comment]
For displaying last update timestamps, it now relies on your browser settings and not anymore the Domoticz language settings.
I hope it will be fine for you.

**Comment by DeKnep** [comment]
Yep, that works too :) Thanks!

**Comment by DeKnep** [comment]
Something's still not quite right... On the Utility tab I have few devices that are updated very frequently (power and voltage readings from my smart meter). With every update, the "heartbeat" icon in front of the timestamp briefly disappears and the timestamp is shown including seconds. The icon then immediately reappears and the timestamp is shown without seconds again.
That's rather annoying because it's very uneasy on the eyes.
At first I thought this was some kind of browser caching issue, but it's not. It happens in both Firefox and Chrome, even after completely clearing the cache, offline data, etc.

**Comment by davidlb** [comment]
I canot do anything because the way it's updated in Domoticz, I have to overwrite it after and so there is a kind of flickering
