### ISSUE TITLE
No header in mobile browser

### ISSUE THREAD

**Issue by Plantje1978** [domoticz/Machinon#41]
The application defaults to the dashboard and that is ok. However, no header is shown on a mobile device, I cannot get to another tab. Refreshing the page used to give me the header back. But it doesn't do that anymore.

This happens on Edge on a Samsung Galaxy S20+. Tested Chrome as well and there the refreshing does give the header back.

Using the 1.16.2 beta and had this issue in 1.16.1 as well.

**Comment by davidlb** [comment]
I'm not able to reproduce it, I need your help:
What options did you enable?
Did you try to reset the cache / theme?

**Comment by Plantje1978** [comment]
Do you get the header on first load? I never got that on my mobile device
What browser do you use? Edge or Chrome?
I need to Google how to reset the cache on my mobile. Since, there is no header, I cannot go to the settings to reset the theme :)

I will login to this issue on my mobile and see if I can share some screen shots

**Comment by davidlb** [comment]
To clear cache, edit URL to replace #Dashboard with #Setup, it should do the trick to go to the Theme settings.

**Comment by Plantje1978** [comment]
Nevermind.... you gave the notch in the right direction.

I opened the website in desktopmode on my mobile. Now I did get the header, was able to go to the settings and got the popup to reset the theme. Not only is the header back. Not it is even not needed anymore to do a refresh to get the header. Thanks for thinking along and thanks for this great theme!

**Comment by davidlb** [comment]
Great news! Thanks four your reply.
Time to release v1.16.2
