### ISSUE TITLE
Poll: Should we keep notifications feature?

### ISSUE THREAD

**Issue by davidlb** [domoticz/Machinon#43]
IMHO, notifications should be managed globally by Domoticz and not on the browser side.
What do you think?
Do you use Notifications? And what for?

**Comment by EdddieN** [comment]
I personally do not use the notifications as most of the time the system is doing its things on the background while I’m not looking at it. 

Lately all the notifications I use I have connected them to Telegram so..... I guess any notification should really be handled by Domoticz?

**Comment by DewGew** [comment]
There is is custom notifications like "machinon update availible", "theme settings saved" e.t.c I think those are needed. There is also browser notification when a switch is turned on or off those I dont use at all and those are now added in domoticz.

**Comment by DewGew** [comment]
I vote for removal.

**Comment by Xenomes** [comment]
Nope don't use it, only for update notification.

**Comment by Rouzax** [comment]
Also don't use it.

**Comment by chrislader** [comment]
Agree, kill it. 
Don't use it either.

**Comment by davidlb** [comment]
Hey guys, I'm currently moving to Home Assistant so I won't probably spend anymore time on this project unless I'm too disappointed by HA and go back to Domoticz but for the moment, I enjoy HA and all its integrations (devices) and cards (UI widgets) @EdddieN @DewGew

**Comment by EdddieN** [comment]
Hello @davidlb 

Great to hear from you! I also have been quite a bit out of the scene of Home Automation in general, although still with Domoticz. 

I'm sure your input will be missed! Many thanks for all your effort and help 😃

**Comment by DewGew** [comment]
I can remove notification system (the bell) and use Domoticz native system for notify updates, low battery, save settings etc.

**Comment by EdddieN** [comment]
Yes, I think the simpler and more inline with Domoticz native them the easier will be to maintain
