### ISSUE TITLE
Little ccs issue in the dark theme 

### ISSUE THREAD

**Issue by Xenomes** [domoticz/Machinon#5]
On some places the white text is hard to read, in de dark theme.
Events => Vaules
![afbeelding](https://user-images.githubusercontent.com/11648297/78063122-f5d33a80-738f-11ea-98e8-45df325bbdef.png)

Roomplan => add device
![afbeelding](https://user-images.githubusercontent.com/11648297/78063321-4e0a3c80-7390-11ea-8d8d-02be756033cf.png)

**Comment by Xenomes** [comment]
I did a little hobby :)

`.odd{
   --main-text-color: #515558;
}

.dataTables_wrapper{
    background-color: #E8E8E8;;
}
`

**Comment by davidlb** [comment]
thanks, I'll take a look at it :)

**Comment by davidlb** [comment]
Fixed with commit 77feb66e3f5e71ae64bb33a232a5e333f595f712

**Comment by davidlb** [comment]
Thanks for your report
Fixed in 1.15.5
