### ISSUE TITLE
Graphs not showing: typeError moment.tz is not a function

### ISSUE THREAD

**Issue by josemi73** [domoticz/Machinon#51]
After updating domoticz, graphs are missing (humidity, temperature, ...). I think that in domoticz has been added the chance to select hours, days, I do not know if it could be the origin. I have uploaded the error shown in browser developer tools.
Thank you

![image](https://user-images.githubusercontent.com/52371223/98437334-94233d80-20e1-11eb-9508-057cc8772aa2.png)

[EDIT]
Perhaps this could be the solution:
https://stackoverflow.com/questions/47046067/typeerror-moment-tz-is-not-a-function

**Comment by kitopopo** [comment]
Dear friends,

I also have the same problem. i can not see any temperatura graphics. I hope you solve the problem soon. Thanks in advanced

**Comment by kitopopo** [comment]
Dear friend,

Gizmo Cruz tells me that changes have been made to improve the domoticz gui, when you can and have time, please, we would appreciate the machinon update. Thank you very much in advance, 

best regards

**Comment by kitopopo** [comment]
Dear friends,

9 days later we still cannot use the graphics in domoticz with the machinon theme, any news? no changes in github and some updates in domoticz but the problem is not solved.

thank in advanced

**Comment by laoil72** [comment]
Same problem with last bêta

**Comment by kitopopo** [comment]
Dear @DewGew , @davidlb ,@EdddieN , @landaisbenj 

Have you seen the problem of the machinon theme? can someone of you solve it? We would be very grateful, thanks in advance. a cordial greeting

![temp](https://user-images.githubusercontent.com/51416982/99400517-56939100-28e7-11eb-8cf2-35d97f1b5de9.jpg)

**Comment by laoil72** [comment]
@gizmocuz Can you help us ? Thanks

**Comment by kitopopo** [comment]
> @gizmocuz Can you help us ? Thanks

Hi, we also reported this problem directly to domoticz 9 day ago. You can find some more information here, but no solution

`https://github.com/domoticz/domoticz/issues/4453`

I'm tired of asking for help but no one responds heare in this issue. I do not understand what is happening. Hope someone can help us soon

regards

**Comment by davidlb** [comment]
Hi, I moved to HomeAssistant and so do not work anymore on this Domotiz theme. I hope @DewGew might help you.

**Comment by kitopopo** [comment]
Dear @DewGew, please help us. Thanks in advanced. Best regards

**Comment by gizmocuz** [comment]
@kitopopo , Please use one of the default themes , like the 'default'
As it seems davidlb moved over to another home automation system, and he was the author of the theme,
It is best to close that repository as it will not be maintained anymore
There are alternatives, but the easiest is to just stick to the default theme

**Comment by DewGew** [comment]
I dont have any issues with graphs. Im running machinon v1.16.2 and latest domoticz beta

**Comment by josemi73** [comment]
@DewGew I have just upgraded to the latest domoticz beta, and I am using machinon v1.16.2, but graphs like temperature are not shown, and I am getting the errors that I pasted in the first post.
I am using last version of Chrome Browser.

**Comment by kitopopo** [comment]
Dear @DewGew,

I just upgraded to beta and no graphics are showing. I have tested the lastest versions  of chrome from windows 10, on firefox from windows 10 and chromium from a raspian buster. 

Could you have contact with @gizmocuz  to comment on the latest changes on the beta versions of domoticz to try solve the problem? 

Many people would be very grateful, thank you for your dedication and collaboration, also to @gizmocuz . many thanks.

Best regards

**Comment by gizmocuz** [comment]
@kitopopo , Try upgrading to the 'beta'

**Comment by kitopopo** [comment]
> @kitopopo , Try upgrading to the 'beta'

Dear @gizmocuz ,

I am currently in the last beta of domoticz.

Version: 2020.2 (build 12689)
Build Hash: 13b9181b2-modified
Compile Date: 2020-11-19 11:13:54
dzVents Version: 3.0.16
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

Regards

**Comment by Rouzax** [comment]
I'm also on the latest beta with the latest Machinon and graphs stay empty
![image](https://user-images.githubusercontent.com/4103090/99798701-c09f7680-2b31-11eb-8e5a-4a267826e36d.png)

Looks to be because Domoticz added 
![image](https://user-images.githubusercontent.com/4103090/99798807-ea589d80-2b31-11eb-86a5-7e75d5f5ee31.png)

**Comment by kitopopo** [comment]
Dear @EdddieN ,


Thank you very much for the machinon update, now the graphics work again, you have been very kind, I will test them carefully. A cordial greeting

**Comment by josemi73** [comment]
I had the version 1.16.2, but I did git pull, and it is working now. Currently, it keeps in version 1.16.2
Thank you

**Comment by laoil72** [comment]
Thanks a lot !!!

**Comment by Rouzax** [comment]
@EdddieN It is not fully solved yet.
The initial view will show the graphs 
![image](https://user-images.githubusercontent.com/4103090/100217171-70e6f380-2f13-11eb-931a-3583c2eb88c4.png)

When I zoom in on a section it will be empty again
![Domoticz](https://user-images.githubusercontent.com/4103090/100217889-46496a80-2f14-11eb-8f77-37306964a701.gif)

**Comment by DewGew** [comment]
@Rouzax  Domoticz Beta or stable?  Machinon latest beta or latest master?

**Comment by Rouzax** [comment]
Running Domoticz Beta and Machinon Beta
```
pi@domoticz:~/domoticz/www/styles/machinon $ git branch
* beta
  master
pi@domoticz:~/domoticz/www/styles/machinon $
```

**Comment by DewGew** [comment]
It works only if you dont select  any. This is a new issue. make new issue

**Comment by kitopopo** [comment]
Dear @EdddieN ,

I have updated to Machinon theme V.1.17.1 and no graphic appears again, all graphics are empty. Same problem that 22 days ago, can you solve the problem? thanks in advanced. Best regards.

**Comment by DewGew** [comment]
> Dear @EdddieN ,
> 
> 
> 
> I have updated to Machinon theme V.1.17.1 and no graphic appears again, all graphics are empty. Same problem that 22 days ago, can you solve the problem? thanks in advanced. Best regards.

Are you running domoticz stable or beta?

**Comment by kitopopo** [comment]
> > Dear @EdddieN ,
> > 
> > 
> > 
> > I have updated to Machinon theme V.1.17.1 and no graphic appears again, all graphics are empty. Same problem that 22 days ago, can you solve the problem? thanks in advanced. Best regards.
> 
> Are you running domoticz stable or beta?

Hi, i am running the lastest domoricz beta. Regards

**Comment by kitopopo** [comment]
> > Dear @EdddieN ,
> > I have updated to Machinon theme V.1.17.1 and no graphic appears again, all graphics are empty. Same problem that 22 days ago, can you solve the problem? thanks in advanced. Best regards.
> 
> Are you running domoticz stable or beta?

Dear friend,

I have tested also the lastest machinon beta v1.17.1 with my lastest domoticz beta Version: 2020.2 (build 12709) but the problem is the same, the graphics are dissapeared. Any solution? thanks in advanced

**Comment by kitopopo** [comment]
> > Dear @EdddieN ,
> > I have updated to Machinon theme V.1.17.1 and no graphic appears again, all graphics are empty. Same problem that 22 days ago, can you solve the problem? thanks in advanced. Best regards.
> 
> Are you running domoticz stable or beta?

Hello, for the beta version of domoticz I am using the beta version of machinon but the graphics are not shown,  
I have the latest betas of both versions and it doesn't work any solution? thanks in advanced

**Comment by laoil72** [comment]
Always the same problem...

**Comment by laoil72** [comment]
@EdddieN Hello, allways KO with lastest update

**Comment by DewGew** [comment]
Problems with graph and running on domoticz beta use machinon latest beta v1.17.2

**Comment by kitopopo** [comment]
Solved for me, i have updated to lastest beta and the graphics works correctly now. thanks

**Comment by josemi73** [comment]
Working fine again, thank you.
