### ISSUE TITLE
Visual bug dark theme tiles

### ISSUE THREAD

**Issue by Anjerlaan** [domoticz/Machinon#54]
Hi,

I am using your theme quite a while now. Mainly the dark theme.
Recently I installed 16.2, but I notice an artifact in 50% of the device tiles.
E.g. Yeelight TV top right tile.

![EE195DFF-1D89-4FAF-9E1C-64C22A3903E5](https://user-images.githubusercontent.com/18295963/99870357-ba150b80-2bd2-11eb-9fac-5fe8b832896d.png)

I have already tried to reset/update (the browser cache) the theme as described because some icons were not updated. Those were updated after the reset, but the artifact remained.

**Comment by DewGew** [comment]
Only in darktheme?

**Comment by Anjerlaan** [comment]
Yes, but after you mentioned this, in both the white and dark theme some of the tiles are missing the ON/OFF text label. The ones that in the dark theme don’t have the artifact

![9034F51D-2DF0-49A2-B536-574945AEEAA0](https://user-images.githubusercontent.com/18295963/99873850-2a2b8d80-2be3-11eb-9278-d38ba433415a.png)

**Comment by DewGew** [comment]
On/off label you can set in the theme settings " Switch Instead of Text"

**Comment by Anjerlaan** [comment]
> On/off label you can set in the theme settings " Switch Instead of Text"

That is not what I mean.
Next to the 3 dots, text (Uit or percentage) is displayed only for certain devices not all...is that deliberately?
Also left from the 3 dots and “Uit” is the artifact (in dark theme) looks like a cylinder.
Is that also deliberately?

**Comment by DewGew** [comment]
> > On/off label you can set in the theme settings " Switch Instead of Text"
> 
> That is not what I mean.
> Next to the 3 dots, text (Uit/Aan or percentage) is displayed only for certain devices not all...is that deliberately?
> Also left from the 3 dots and “Uit” or percentage is the artifact (in dark theme) looks like a cylinder.
> Is that also deliberately? This cylinder is not visible in the white theme

But this is correct Text or switch you can choose from. About the cylinder i think its not suppost to be there. I look into this.

**Comment by Anjerlaan** [comment]
> > > On/off label you can set in the theme settings " Switch Instead of Text"
> > 
> > 
> > That is not what I mean.
> > Next to the 3 dots, text (Uit/Aan or percentage) is displayed only for certain devices not all...is that deliberately?
> > Also left from the 3 dots and “Uit” or percentage is the artifact (in dark theme) looks like a cylinder.
> > Is that also deliberately? This cylinder is not visible in the white theme
> 
> But this is correct Text or switch you can choose from. About the cylinder i think its not suppost to be there. I look into this.

On my laptop, the internet browsers (Chrome & Firefox) show the dark theme UI correct now (after several resets)...no visual "cylinders" anymore.

The iPad still has the "cylinder" problem, also after several times clearing cache or resets
