### ISSUE TITLE
Theme wont load fully, isn't functional

### ISSUE THREAD

**Issue by StRess691** [domoticz/Machinon#56]
Hi. I added this to a different Issue, but at the end I believe, that this is something new/different.
I used Machinon theme from this git repository: https://github.com/EdddieN/machinon-domoticz_theme.git

I tried switching to new git, for newer version, but as soon as I installed it, the whole GUI is broken. Both on mobile and PC.

What I made:
- originally installed theme from first git in ~/domoticz/www/styles/machinon
- installed theme from new git to ~/domoticz/www/styles/machinon_2
- cleared browser cache and tried to open domoticz in inclognito mode - without success - still elements of the GUI are missing
- removed original theme
- removed new theme
- installed new theme in ~/domoticz/www/styles/machinon
- cleared browser cache
- searched for the domoticz.js.gz file, but there is now in directory ~/domoticz/www/js, only domoticz.js is present
- I can not go to Setup / Parameters / Theme and reset the theme, because when it is enabled, there is still standard domoticz no machinon menu and theme tab is missing.
- tried to use Theme Manager plugin, but also without success.
- apt-get update + apt update and upgrade already made.

Unfortunately all the above without any success - I still have broken GUI. I still can install old theme and it work fine for me. How can I debug it?

![image](https://user-images.githubusercontent.com/63842522/99881442-3121c280-2c1a-11eb-9535-69f0394475dc.png)

When I investigate with use of Chrome tools, I get with the new theme this errors:
![image](https://user-images.githubusercontent.com/63842522/99881491-6b8b5f80-2c1a-11eb-9a08-2734c927c033.png)

**Comment by StRess691** [comment]
PS 
It is working totally fine on old machinon version 1.15.3.
I'm running this on Rpi 3b+

**Comment by DewGew** [comment]
What domoticz version do you use?

**Comment by StRess691** [comment]
Version: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by BreizhCat** [comment]
Hello

Same issue there after last pull.
I'm using :
Version: 2020.2 (build 12213)
Build Hash: be4889e5d-modified
Compile Date: 2020-07-08 21:31:18
dzVents Version: 3.0.11
Python Version: 3.5.1 (default, Jan 29 2018, 14:18:59) [GCC 4.9.3 20150311 (prerelease)]

On synology.

Thanks for your help

**Comment by StRess691** [comment]
Checked now on newly installed Ubuntu. I installed newest Domoticz and Machinon - no luck. This same issue. However, when I updated Domoticz to the Beta version, everything seams to work fine.

**Comment by DewGew** [comment]
**If you are using Domoticz stable use Machinon msater. If you are using Domoticz Beta use Machinon beta!!!**

**Comment by BreizhCat** [comment]
Works fine now with the last pull. Thanks for your help !

**Comment by StRess691** [comment]
Can confirm. With latest pull the theme is working. 
This comment anyhow:
> **If you are using Domoticz stable use Machinon master. If you are using Domoticz Beta use Machinon beta!!!**
> This is because moment.js is added to Domoticz Beta

 is necessary, but in the installation manual. It has and had nothing to do with our issues. Repairing the theme was the case. Earlier the theme (beta AND master) was working only with beta installation of Domoticz.
