### ISSUE TITLE
Graphs not working on Domoticz Beta when selecting range

### ISSUE THREAD

**Issue by Rouzax** [domoticz/Machinon#58]
The initial view will show the graphs 
![image](https://user-images.githubusercontent.com/4103090/100217171-70e6f380-2f13-11eb-931a-3583c2eb88c4.png)

When I zoom in on a section it will be empty again
![Domoticz](https://user-images.githubusercontent.com/4103090/100217889-46496a80-2f14-11eb-8f77-37306964a701.gif)

Running Domoticz Beta and Machinon Beta
```
pi@domoticz:~/domoticz/www/styles/machinon $ git branch
* beta
  master
pi@domoticz:~/domoticz/www/styles/machinon $
```

**Comment by DewGew** [comment]
This is a Domoticz issue

**Comment by Rouzax** [comment]
You want me to open a ticket on the domoticz issues?

**Comment by Rouzax** [comment]
@DewGew It looks to be solved in the latest Domoticz beta update

**Comment by Rouzax** [comment]
Sorry cheered to early, still the same issue.

**Comment by Tinus016** [comment]
Are you sure this is a domoticz issue? I've installed temporary a default theme and Graps while sho up. When I select the Machinon theme it doesn't work anymore.

<img width="1187" alt="Schermafbeelding 2020-12-05 om 17 41 09" src="https://user-images.githubusercontent.com/60196891/101258262-a82e7f00-3721-11eb-8047-166cec4caaaf.png">
<img width="1325" alt="Schermafbeelding 2020-12-05 om 17 41 40" src="https://user-images.githubusercontent.com/60196891/101258270-b381aa80-3721-11eb-99ce-af5e2fdfb641.png">

**Comment by DewGew** [comment]
> Are you sure this is a domoticz issue? I've installed temporary a default theme and Graps while sho up. When I select the Machinon theme it doesn't work anymore.
> 
> 
> 
> <img width="1187" alt="Schermafbeelding 2020-12-05 om 17 41 09" src="https://user-images.githubusercontent.com/60196891/101258262-a82e7f00-3721-11eb-8047-166cec4caaaf.png">
> 
> <img width="1325" alt="Schermafbeelding 2020-12-05 om 17 41 40" src="https://user-images.githubusercontent.com/60196891/101258270-b381aa80-3721-11eb-99ce-af5e2fdfb641.png">
> 
> 

Read the first post again.
