### ISSUE TITLE
Dimmer slider misalignment on ipad 2

### ISSUE THREAD

**Issue by keesdekraker** [domoticz/Machinon#6]
The dimmer slider seems to be misaligned on a ipad 2 tablet.
The misalignment does not seem browser related. It seems consistent on different browser on the same device.
The problem seems to be limited to this device, since other devices show the slider in the right position.
![20200330_214040](https://user-images.githubusercontent.com/36312068/78503540-8383a100-7767-11ea-8032-cb46549135f7.jpg)

**Comment by davidlb** [comment]
I dont have ipad, it will be difficult to fix it on my side :/

**Comment by davidlb** [comment]
I tried to cleanup and rewrite part of the slider, give me your feedback. It's currently in beta branch and will be in V1.16.

**Comment by davidlb** [comment]
New version have been released, can you give it a try?

**Comment by keesdekraker** [comment]
Thanks! Have tried V1.16.1 this morning. Without succes however. Position of the slider is still incorrect.
Other devices (android 7" tablet, Galaxy phone, laptop) don't show this issue.  I'll look into it after the holidays.
