### ISSUE TITLE
Graphs not working on Domoticz

### ISSUE THREAD

**Issue by Tinus016** [domoticz/Machinon#68]
Hello, I've an issue whit the new version of the Machinon Theme. The Graphs dont work anymore, I also posted this issue in issue #58 but this issue is about the zoom effect. In my case the whole graphs won't work anymore. When I switch to a default theme and graphs will show up. Can someone explain this to me, what do I wrong? I tried everything, clear chases reset theme and reinstall the theme but without success.

<img width="1349" alt="Schermafbeelding 2020-12-08 om 23 03 26" src="https://user-images.githubusercontent.com/60196891/101546793-9b23c100-39a9-11eb-8359-a6988d0ce66d.png">

Domoticz version:

<img width="418" alt="Schermafbeelding 2020-12-08 om 23 04 22" src="https://user-images.githubusercontent.com/60196891/101546897-c1e1f780-39a9-11eb-9784-0dafd999d669.png">

Thanks for your effort!

**Comment by snelroy** [comment]
I have exactly the same problem, no graphs.
Other themes have no problem with the graphs.

**Comment by kitopopo** [comment]
Same problem, For the beta version of domoticz I am using the beta version of machinon but the graphics are not shown,
I have the latest betas of both versions and it doesn't work any solution? thanks in advanced

**Comment by Anjerlaan** [comment]
Same problem here...also browser cash problems on only iPad, when I switch to default theme everything is ok...which version do you guys run?
I find it strange that I am on 1.17.1 while the official release is still on 1.16.2

**Comment by DewGew** [comment]
Problems with graph and running on domoticz beta use machinon beta

**Comment by Anjerlaan** [comment]
> Problems with graph and running on domoticz beta use machinon latest beta v1.17.2

Thanx, working!

**Comment by kitopopo** [comment]
Solved for me, i have updated to lastest beta and the graphics works correctly now. thanks

**Comment by Tinus016** [comment]
> Problems with graph and running on domoticz beta use machinon latest beta v1.17.2

Thanks that works out for me!

**Comment by DarkAllMan** [comment]
For me this is still not working.
![afbeelding](https://user-images.githubusercontent.com/1582343/103412568-06f6e500-4b76-11eb-98bc-dd55d1890785.png)
