### ISSUE TITLE
Reports and info disappeared again.

### ISSUE THREAD

**Issue by Rouzax** [domoticz/Machinon#7]
**Domoticz**
```
Version: 2020.1 (build 11925)
Build Hash: 87bad52e2
Compile Date: 2020-04-09 08:57:13
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```

**Machinon**
```
pi@domoticz:~/domoticz/www/styles/Machinon $ git show --oneline -s
44f2e56 (HEAD -> master, origin/master, origin/HEAD) Update README.md
```

Cleared out Browser Cache, Tried incognito.

![image](https://user-images.githubusercontent.com/4103090/78881878-b1166600-7a57-11ea-80d2-d32c4230a0c1.png)

**Comment by Rouzax** [comment]
Hold my horses 🐴 
They are only not showing on the Dashboard page, is that intended?

**Comment by davidlb** [comment]
On the dahboard, it's the same logic as the default theme to display only main information.
