### ISSUE TITLE
Console errors: Graphs not working

### ISSUE THREAD

**Issue by DarkAllMan** [domoticz/Machinon#72]
My graphs for energy consumption are not working.
Console shows these errors:

`TypeError: moment.tz is not a function
    timezoneOffsetFunction highcharts-8.2.2-patch.9612.src.js:10162
    set highcharts-8.2.2-patch.9612.src.js:10033
    getTimeTicks highcharts-8.2.2-patch.9612.src.js:10365
    getTimeTicks highcharts-8.2.2-patch.9612.src.js:20631
    setTickPositions highcharts-8.2.2-patch.9612.src.js:15873
    setTickInterval highcharts-8.2.2-patch.9612.src.js:15800
    setScale highcharts-8.2.2-patch.9612.src.js:16154
    redraw highcharts-8.2.2-patch.9612.src.js:28088
    redraw highcharts-8.2.2-patch.9612.src.js:28082
    redrawChart RefreshingChart.js:278
    refreshChartData RefreshingChart.js:264
    Angular 40
    execCb require.min.js:5
    check require.min.js:5
    enable require.min.js:5
    bind require.min.js:5
    emit require.min.js:5
    each require.min.js:5
    emit require.min.js:5
    check require.min.js:5
    enable require.min.js:5
    bind require.min.js:5
    emit require.min.js:5
    each require.min.js:5
    emit require.min.js:5
    check require.min.js:5
    enable require.min.js:5
    bind require.min.js:5
    emit require.min.js:5
    each require.min.js:5
    emit require.min.js:5
    check require.min.js:5
    enable require.min.js:5
    bind require.min.js:5
    emit require.min.js:5
 Possibly unhandled rejection: {}`

**Comment by superjunky** [comment]
+1

I get the same errors.

**Comment by laoil72** [comment]
Hello, i have the same problem with no graphic with Beta AND Master.

Version: 2020.2 (build 12873)
Build Hash: 4548816ba-modified
Compile Date: 2021-01-21 19:51:26
dzVents Version: 3.1.2
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

Machinon theme V.1.15.3

**Comment by JanZorz** [comment]
yup, similar error and graphs doesn't show. It's... annoying :(

**Comment by DarkAllMan** [comment]
There does not seem to be much development in the beta branch.....?

**Comment by DewGew** [comment]
fixed in latest
