### ISSUE TITLE
Multiple graph's not showing data after Domoticz update 2021.1

### ISSUE THREAD

**Issue by Xtremernl** [domoticz/Machinon#81]
After updating to Domoticz version 2021.1 the graphs are not showing the line's.
The same issue as #73 

But it's not only for the temperature, but also for other measurements.

-	temperature
-	Power (Watt)
-	Amperage
-	Voltage
-	Ping time’s
-	Solarpower

If i use a other theme, there is no issues with the graph's.

Domoticz Info : 

Version: 2021.1
Build Hash: 8547c5b7e
Compile Date: 2021-04-17 17:29:11
dzVents Version: 3.1.7
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by slawkory** [comment]
I am observing the same after upgrade of domoticz.

**Comment by averni59** [comment]
I do have the same issue with the same build hash (8547c5b7e).

**Comment by fueryon** [comment]
quickfix:
comment out this part of code in custom.js file (from line 24):
```
$.ajax({	
    url: "acttheme/js/moment.js",	
    async: false,	
    dataType: "script",	
});
```
domoticz loads moment with tz addon when page is loading, this snipppet causes moment to reload, but without tz extension

**Comment by averni59** [comment]
> quickfix:
> comment out this part of code in custom.js file (from line 24):
> 
> ```
> $.ajax({	
>     url: "acttheme/js/moment.js",	
>     async: false,	
>     dataType: "script",	
> });
> ```
> 
> domoticz loads moment with tz addon when page is loading, this snipppet causes moment to reload, but without tz extension

This fix works for me :-)
Thank you !

**Comment by waltervl** [comment]
Using the beta branch of this theme perhaps also works as this change executed there

**Comment by tkorstanje** [comment]
I've been using 1.17.1 (the current beta), but have experienced the same problem as mentioned here since the update to 2021.1. But also in 1.17.1 the quick fix works like a charm!

**Comment by altserg** [comment]
I have applied the quick fix. I can see the data, but the there overall started to look ugly, some menu items are missing. See pictures before and after. Is there any proper fix ?

Before the fix:
![image](https://user-images.githubusercontent.com/79573763/133407676-4be65f4e-1f38-48ef-b8be-6a002e9242a2.png)

After the fix:
![image](https://user-images.githubusercontent.com/79573763/133407404-f14ef8a8-933e-4395-a6db-dbb9f37a2e16.png)
