### ISSUE TITLE
after update domoticz to 13680 machinon theme is deconfigured and the theme settings button is lost

### ISSUE THREAD

**Issue by kitopopo** [domoticz/Machinon#89]
Dear friends, afeter update domoticz to 13680 is impossible be able to configure the machinon theme in domoticz.
the theme configuration button is missing. can someone fix the problem? It is the favorite subject of many people. they comment on some of the problem in the domoticz forum

https://www.domoticz.com/forum/viewtopic.php?f=6&t=37117
![10](https://user-images.githubusercontent.com/51416982/135761914-0515e24c-20c5-408e-b7d3-8d008a9ec3bc.jpg)

![11](https://user-images.githubusercontent.com/51416982/135762000-8a43c7e2-7510-482d-af39-737f76f50050.jpg)

**Comment by kitopopo** [comment]
Hopefully @DewGew  can fix this as with a similar issue that occurred in late 2019. Thank you so much in advance. a cordial greeting

**Comment by kiddigital** [comment]
@DewGew  or @EdddieN , with Domoticz [url=https://github.com/domoticz/domoticz/pull/4942]PR 4942[/url], the way Domoticz processes theme files has been changed.

Domoticz no longer depends on the virtual _acttheme_ directory, which it rewrote each time to 'styles/<theme>'. But as at the moment the Machinon theme _depends_ on this, the theme files do not get loaded anymore as Domoticz now tries to load these files from the (non-existing) _acttheme_ directory, resulting in 404 (file not found) for certain resources.

See also [url=https://www.domoticz.com/forum/viewtopic.php?f=6&t=37117]this[/url] forum topic.

**Comment by kitopopo** [comment]
Dear friends @kiddigital @DewGew @EdddieN ,

I confirm that the graphs are not shown in domoticz . the same as in the previous  issue,Graphs not working on Domoticz #68.
hope someone can solve the problem soon. Thank you very much in advance.

Best regards

**Comment by jordipalet** [comment]
This worked for me with Chrome:

1) cd ~/domoticz/www/styles/machinon/js
2) mv moment.js old-moment.js
3) wget https://momentjs.com/downloads/moment.min.js
4) service domoticz restart

(before I tried clearing caches in the browser, etc. - but nothing worked)

**Comment by kitopopo** [comment]
> This worked for me with Chrome:
> 
> 1. cd ~/domoticz/www/styles/machinon/js
> 2. mv moment.js old-moment.js
> 3. wget https://momentjs.com/downloads/moment.min.js
> 4. service domoticz restart
> 
> (before I tried clearing caches in the browser, etc. - but nothing worked)

oh yea, thanks, this also works for me. I don't understand why it is not incluied in the lastest beta or master version in order to solve the problem for all users. Thanks, best regards
